### PR TITLE
New version, or should I fork?

### PR DESCRIPTION
**Pull request by yanick**
Hi, this is not a straight pull request, but more of a question/request. 

I'm working on a total rewrite of the tool for V3 of the github api. The commands of `gh` will remain the same, but the guts are going to be quite different (you can see the code of this branch to have an idea where I'm going).  While I'm having comaint of the module, I'm not the original author, so I'm honor-bound to ask: are you guys okay with me changing the core of the module that much, or would I be better to fork the mutated codebase as a brand-new distro?

### CODE REVIEW

**Comment by c9s** [comment]
Hi Yanick,

I am totally ok with the guts changes!

Thank you for putting the efforts on this!


Yanick Champoux <notifications@github.com>於 2017年2月13日 週一，01:53寫道：

**Comment by c9s** [comment]
Merged! THANKS!

**Comment by c9s** [comment]
Hi @yanick I just added you to the collaborators, you can now commit to the repo directly.

**Comment by yanick** [comment]
Thank you! Both for the vote of confidence and the commit bit! :-)

My branch is nowhere done. My goal is to make a first pass to have all commands at least be functional before merging back to master/dev. I'm aiming to have that done this week. So... stay tuned for further development!

**Comment by c9s** [comment]
@yanick looking forward to the further development! :D

**Comment by yanick** [comment]
Heh, thanks! And sorry, I got sidetracked by other projects. >.>

**Pull request merged**
